auto_fix_minimise: true
barostat_frequency: 25
beutler_alpha: 0.5
beutler_fix_epsilon: true
charge_difference: null
charge_scale_factor: 0.2
checkpoint_frequency: 500 ps
coalchemical_restraint_dist: null
com_reset_frequency: 10
constraint: h_bonds
cutoff: "10 \xC5"
cutoff_type: pme
dynamic_constraints: true
energy_frequency: 1 ps
equilibration_constraints: true
equilibration_time: 500 ps
equilibration_timestep: 0.002 ps
fix_perturbable_zero_sigmas: true
frame_frequency: 250 ps
gcmc: false
gcmc_bulk_sampling_probability: 0.1
gcmc_excess_chemical_potential: -6.09 kcal mol-1
gcmc_frequency: null
gcmc_num_waters: 20
gcmc_radius: "4 \xC5"
gcmc_selection: null
gcmc_standard_volume: "30.543 \xC5^3"
gcmc_tolerance: 0.0
ghost_modifications: false
h_mass_factor: 1.5
hmr: true
include_constrained_energies: false
integrator: langevin_middle
lambda_energy: null
lambda_schedule: standard_morph
lambda_values: null
log_file: log.txt
log_level: debug
max_gpus: 4
max_sire_threads: null
max_threads: 32
minimisation_constraints: false
minimisation_errors: false
minimise: true
null_energy: 1e+06 kcal mol-1
num_checkpoint_workers: null
num_energy_neighbours: 5
num_lambda: 11
opencl_platform_index: 0
output_directory: mdm2_e23g_open_conf_am7209_short_run
oversubscription_factor: 1
overwrite: false
page_size: null
pert_file: null
perturbable_constraint: h_bonds_not_heavy_perturbed
perturbed_system: null
platform: cuda
pressure: 1 atm
randomise_velocities: false
replica_exchange: true
rest2_scale: 1.0
rest2_selection: null
restart: false
restraints: null
runtime: 500 ps
save_crash_report: false
save_energy_components: true
save_trajectories: true
save_velocities: false
save_xml: true
shift_coulomb: "1 \xC5"
shift_delta: "1.5 \xC5"
softcore_form: zacharias
somd1_compatibility: false
surface_tension: null
swap_end_states: false
taylor_power: 1
temperature: 300 K
terminal_flip_angle: null
terminal_flip_frequency: null
terminal_flip_max_mobile_atoms: null
timeout: 3e+14 ps
timestep: 0.004 ps
use_backup: false
use_dispersion_correction: false
write_config: true
